flask-oracom-main/OraApp/employers/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect, request, abort
from OraApp import db, bcrypt
from OraApp.forms import User_Login, Employer_Signup, Employer_User_Update, Job_Add, Job_Update, Forgot_Password, Reset_Password, Company_Search
from OraApp.models import User, Employer, Job, jobs_applied, Applicant
from OraApp.utils import save_file, user_role_required, remove_file, send_pwd_reset_email, send_shortlist_email
from flask_login import login_user, current_user

employer = Blueprint('employer', __name__)

# Employer dashboard
@employer.route("/employer/account/")
@user_role_required('employer')
def employer_account():
    user = current_user.employers
    job_posts = user.jobs
    applicants = db.session.query(Applicant).select_from(Applicant).join(jobs_applied).join(Job).filter_by(company=user).all()
    listed = db.session.query(Applicant).select_from(Applicant).join(jobs_applied).filter_by(shortlisted=True).join(Job).filter_by(company=user).all() 

    return render_template("employers/account.html", title="Employer | Account", jobs=job_posts, applicants=applicants, listed=listed)

# Employer/company details
@employer.route("/company/<int:company_id>/profile/")
def profile(company_id):
    company = Employer.query.get_or_404(company_id)
    return render_template("employers/profile.html", title="OraJobs | Company Profile", company=company)

# company list
@employer.route("/companies/")
@employer.route("/company/list/")
def company_list():
    form1 = Company_Search()
    page = request.args.get('page', 1, type=int)
    companies = Employer.query.paginate(page=page, per_page=15)
    head = 'List of Companies'
    return render_template("employers/list.html", title="OraJobs | Companies", companies=companies, head=head, form1=form1)

@employer.route("/employer/jobs/<int:job_id>/details/")
@user_role_required('employer')
def job_details(job_id):
    job = Job.query.get_or_404(job_id)
    if not job.company == current_user.employers:
        abort(403)
    applicants = db.session.query(jobs_applied.c.job_id).filter_by(job_id=job_id).all()

    return render_template("employers/job-details.html", title="OraJobs | Job Details", job=job, applicants=applicants)

@employer.route("/employer/posted-jobs")
@user_role_required('employer')
def posted_jobs():
    user = current_user.employers
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.filter_by(company=user).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15)
    list = db.session.query(jobs_applied.c.job_id, jobs_applied.c.applicant_id, jobs_applied.c.shortlisted)

    return render_template("employers/jobs.html", title="OraJobs | Posted Jobs", jobs=jobs, list=list)

# Jobs posting
@employer.route("/employer/post-jobs/", methods=['GET', 'POST'])
@user_role_required('employer')
def post_jobs():
    user = current_user.employers
    form = Job_Add()
    form.company_id.data = user.id
    if form.validate_on_submit():
        salary = form.salary.data if form.salary.data else 0
        job = Job(title=form.title.data.strip(), category=form.category.data, type=form.type.data, description=form.description.data, salary=salary, company=user)
        db.session.add(job)
        db.session.commit()
        
        flash(f'New Job Added Successfully!', 'success')
        return redirect(url_for('.posted_jobs'))
    h = 'New Job'
    return render_template("employers/post_jobs.html", title="Employer | Post Jobs", form=form, h=h)

@employer.route("/employer/jobs/<int:job_id>/update", methods=['GET', 'POST'])
@user_role_required('employer')
def edit_jobs(job_id):
    job = Job.query.get_or_404(job_id)

    if not job.company == current_user.employers:
        abort(403)

    form = Job_Update()
    if form.validate_on_submit():
        job.title = form.title.data.strip()
        job.category = form.category.data.strip()
        job.type = form.type.data 
        job.description = form.description.data
        job.salary = form.salary.data if form.salary.data else 0

        db.session.commit()
        flash(f'Job Updated Successfully.', 'success')
        return redirect(url_for('.posted_jobs'))
  
    form.title.data = job.title 
    form.category.data = job.category
    form.salary.data = job.salary
    form.type.data = job.type
    form.description.data = job.description
    h = 'Update Job'
    return render_template("employers/post_jobs.html", title="Employer | Update Job", form=form, job=job, h=h)

@employer.route("/employer/<int:job_id>/remove-job/", methods=['POST'])
@user_role_required('employer')
def remove_job(job_id):
    job = Job.query.get_or_404(job_id)
    if not job.company == current_user.employers:
        abort(403)

    db.session.delete(job)
    db.session.commit()
            
    flash(f'Job Removed Successfully!', 'success')
    return redirect(url_for('.posted_jobs'))

@employer.route("/employer/applicants/")
@user_role_required('employer')
def applicants():
    user = current_user.employers
    page = request.args.get('page', 1, type=int)

    query = db.session.query(Applicant, Job, jobs_applied.c.shortlisted, jobs_applied.c.date_applied).select_from(Applicant).join(jobs_applied).order_by(jobs_applied.c.date_applied).join(Job).filter_by(company=user).paginate(page=page, per_page=15)

    return render_template("employers/candidates.html", title="Employer | Applicants", applicants=query)

@employer.route("/employer/applicants/<int:job_id>")
@user_role_required('employer')
def applicants_per_job(job_id):
    job = Job.query.get_or_404(job_id)
    page = request.args.get('page', 1, type=int)
    if not job.company == current_user.employers:
        abort(403)
    applicants = db.session.query(Applicant, jobs_applied.c.shortlisted, jobs_applied.c.date_applied).select_from(Applicant).join(jobs_applied).filter_by(job_id=job_id).join(Job).order_by(jobs_applied.c.date_applied).all()

    return render_template("employers/filtered.html", title="OraJobs | Applicants per Job", applicants=applicants, job=job)

@employer.route("/employer/applicants/shortlisted")
@user_role_required('employer')
def listed_applicants():
    user = current_user.employers
    page = request.args.get('page', 1, type=int)

    query = db.session.query(Applicant, Job).select_from(Applicant).join(jobs_applied).filter_by(shortlisted=True).join(Job).filter_by(company=user).paginate(page=page, per_page=15)

    return render_template("employers/listed.html", title="Employer | Shortlists", applicants=query)

@employer.route("/employer/candidates/")
@user_role_required('employer')
def candidates():
    pass

# Sending emails to shortlisted applicants
@employer.route("/employer/send-message/<int:applicant_id>", methods=['GET', 'POST'])
@user_role_required('employer')
def send_message(applicant_id):
    pass

# Listing candidates and Sending email notifications to shortlisted applicants
@employer.route("/employer/list-applicant/<int:job_id>/<int:applicant_id>")
@user_role_required('employer')
def list_applicant(job_id, applicant_id):
    user = current_user.employers
    job = Job.query.get_or_404(job_id)
    applicant = Applicant.query.filter_by(id=applicant_id).first()
    email=User.query.filter_by(id=applicant.user_id).first().email
    if not job.company == user:
        abort(403)

    db.session.query(jobs_applied).filter((jobs_applied.c.job_id==job_id)&(jobs_applied.c.applicant_id==applicant_id)).update(dict(shortlisted = True))
    list = db.session.query(Job, Applicant, jobs_applied.c.date_applied).select_from(Job).join(jobs_applied).join(Applicant).filter((jobs_applied.c.job_id==job_id)&(jobs_applied.c.applicant_id==applicant_id)).first()

    try:
        send_shortlist_email(email, dict(list))
        db.session.commit()

        flash(' Applicant listed Successfully', 'success')
        return redirect(url_for('.listed_applicants'))
    except:
        flash('Something went wrong! Please Try Again.', 'warning')
        return redirect(url_for('.applicants'))

@employer.route("/employer/list-applicant/<int:job_id>/<int:applicant_id>",  methods=['POST'])
@user_role_required('employer')
def unlist_applicant(job_id, applicant_id):
    user = current_user.employers
    job = Job.query.get_or_404(job_id)
    if not job.company == user:
        abort(403)

    db.session.query(jobs_applied).filter((jobs_applied.c.job_id==job_id)&(jobs_applied.c.applicant_id==applicant_id)).update(dict(shortlisted = False))
    db.session.commit()
    flash('Applicant removed from your list Successfully', 'success')

    return redirect(url_for('.listed_applicants'))

@employer.route("/employer/notifications/")
@user_role_required('employer')
def notifications():
    pass # pass statement is a placeholder & it does not provide any value to the client

# employer account settings
@employer.route("/employer/settings/", methods=['GET', 'POST'])
@user_role_required('employer')
def settings():
    user = current_user.employers
    form = Employer_User_Update()

    if form.validate_on_submit():
        user.name = form.name.data.strip().upper()
        user.user.email = form.email.data.lower()
        user.phone = form.phone.data 
        user.location = form.location.data 
        user.tagline = form.tagline.data 
        user.description = form.description.data 
        user.website = form.website.data 

        if form.logo.data:
            new_file = save_file('employer/logo/', form.logo.data)
            if new_file:
                if user.logo != 'company.png':
                    old_file = f'employer/logo/{str(user.logo)}'
                    remove_file(old_file)
                
                user.logo = new_file

        db.session.commit()
        flash(f'Account Updated Successfully.', 'success')
        return redirect(url_for('.settings'))
  
    form.name.data = user.name 
    form.email.data = user.user.email
    form.phone.data = user.phone
    form.location.data = user.location
    form.tagline.data = user.tagline

flask-oracom-main/OraApp/jobs/routes.py
from OraApp import db
from OraApp.models import Job, jobs_applied, Employer
from flask import render_template, Blueprint, request, abort
from OraApp.forms import Job_Search

jobs = Blueprint('jobs', __name__)

# Job details
@jobs.route("/jobs/<int:job_id>/details/")
def profile(job_id):
    job = Job.query.get_or_404(job_id)
    query = db.session.query(jobs_applied.c.shortlisted).filter_by(job_id=job_id)
    return render_template("jobs/profile.html", title="OraJobs | Job Details", job=job, query=query)

# List of all jobs
@jobs.route("/jobs/")
@jobs.route("/jobs/list/")
def job_list():
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.order_by(Job.date_posted.desc()).paginate(page=page, per_page=15)

    query = db.session.query(Job.category.distinct().label('category'))
    filtered = Job.query
    categories = [row.category for row in query.all()]
    return render_template("jobs/list.html", title="OraJobs | Jobs List", jobs=jobs, filtered=filtered, form1=form1, categories=categories)

@jobs.route("/jobs/categories/")
def categories():
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    query = db.session.query(Job.category.distinct().label('category')).paginate(page=page, per_page=15)
    jobs = Job.query
    categories = [row.category for row in query.items]
    return render_template("jobs/categories.html", title="OraJobs | Jobs Categories", jobs=jobs, form1=form1, categories=categories,pages=query)

# Filter jobs by category
@jobs.route("/jobs/categories/<string:category>")
def filtered(category):
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.filter_by(category=category).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15) or abort(404)
    
    head = f'{category} Jobs'
    return render_template("jobs/filtered.html", title="OraJobs | Jobs List", jobs=jobs, form1=form1, head=head)

# Jobs search
@jobs.route("/jobs/search", methods=['POST'])
def job_search():
    form1 = Job_Search()
    form = request.form
    title_or_category = form['title']
    location = form['location']
    search1 = "%{0}%".format(title_or_category)
    search2 = "%{0}%".format(location)

    page = request.args.get('page', 1, type=int)

    jobs = db.session.query(Job).select_from(Job).filter((Job.title.like(search1) | Job.category.like(search1))).join(Employer).filter(Employer.location.like(search2)).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15) 

    
    locations = f'in "{ location }"' if location else ''
    head = f'Search Results for "{ title_or_category }" {locations}'
    return render_template("jobs/filtered.html", title="OraJobs | Job Search", jobs=jobs, head=head, form1=form1)

flask-oracom-main/OraApp/main/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect
from flask_login import logout_user, current_user

main = Blueprint('main', __name__)

@main.route("/")
def home():
    if current_user.is_authenticated:
        user = current_user.user_role
        return redirect(url_for(f'{user}.{user}_account'))
    return render_template("index.html", title="OraJobs | Home")

@main.route("/about-us")
def about():
    return render_template("about.html", title="OraJobs | About Us")

@main.route("/logout")
def logout():
    logout_user()
    flash(f'Logged Out successfully.', 'primary')
    return redirect(url_for('.home'))

flask-oracom-main/OraApp/templates/about.html
{% extends 'base.html' %}
                          
{% block logged_out %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Home</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('jobs.job_list')}}">Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.company_list')}}">Companies</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('main.about')}}">About Us</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link ps-sm-auto ps-2 dropdown-toggle" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Login</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{{url_for('employer.employer_login')}}">Employer</a></li>
            <li><a class="dropdown-item" href="{{url_for('applicant.applicant_login')}}">Applicant</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{{url_for('admin.admin_login')}}">Admin</a></li>
        </ul>
    </li>
{% endblock %}

{% block container %}
    <section id="about" class="py-5 text-center">
        <div class="container">
            <div class="row m-auto">
                <div class="row m-0 p-0">
                    <div class="col-lg-4 col-md-4 col-12 image-ctn bg-light mb-3">
                        <img class="" src="{{url_for('static', filename='img/hop.jpg')}}" alt="">
                    </div>
                    <div class="col-lg-8 col-md-8 col-12 ">
                        <h2 class=" ">Who We Are</h2>
                        <p>

                            We are proudly part of Oracom Group. Oracom offers outstanding Web Design in Kenya, We are the
                            best Web Design company in Kenya, Canada and Belgium. From Website Builders, Software & Mobile
                            App Development. We stand out in the local and international market to be the best provider of
                            Web Solutions with over 6 Years experience. Always guided by Creative Teams of Web Developers
                            working in both day and night shift arrangement.

                            We are fully charged with the responsibility of developing Quality, Affordable, Effective,
                            Efficient and Reliable Web Solutions to our ever growing wide category of clients. Get the best
                            of our services. <a href="#contact">Contact Us</a> NOW!

                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="services" class="py-5 text-center">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="section-header">
                        <h2 class=" ">What We Do</h2>
                    </div>
                </div>
            </div>
            <div class="row row-cols-lg-3 row-cols-md-2 row-cols-1 g-3">
                <div class="col">
                    <div class="card">
                        <span class="card-icon"><i class="fa fa-code"></i></span>
                        <div class="card-text">
                            <h3>Web Design</h3>
                            <p>
                                Are you searching for Web Design in Kenya? then search no further. Website design and
                                development is our specialty. Do you want out of the box designs, or need an E-Commerce
                                website or a custom web design? Looking for the best Web Design Company in Kenya, then
                                Oracom Web Solutions is your best fit.
                            </p>
                            <a class="btn btn-sm btn-brand peach text-light" href="#" role="button">
                                Learn More
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card">
                        <span class="card-icon"><i class="fa fa-ioxhost"></i></span>
                        <div class="card-text">
                            <h3>Internet Marketing Agency</h3>
                            <p>
                                Arm yourself with the essential principles and practices of marketing in this digital
                                economy by enrolling for our digital marketing courses today. We offer the Best Digital
                                Marketing Training in Kenya
                            </p>
                            <a class="btn btn-sm btn-brand peach text-light" href="#" role="button">
                                Learn More
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card">
                        <span class="card-icon"><i class="fa fa-server"></i></span>
                        <div class="card-text">
                            <h3>Domain Hosting</h3>
                            <p>
                                Oracom Kenya Web Solutions gives you the best combination of power, speed, reliability,
                                security and availability in all domain registration and Web Hosting plans. For the best
                                Domain and Hosting in Kenya
                            </p>
                            <a class="btn btn-sm btn-brand peach text-light" href="#" role="button">
                                Learn More
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="contact" class="py-5 bg-ligvht">
        <div class="container">
            <div class="d-md-flex">

                <div class="social-contact bg-white me-md-2 mb-md-0 mb-3">
                    <div class="git d-flex align-items-center justify-content-between">
                        <ul class="user">
                            <li><a href="tel:+254729990583" target="_blank"><i class="fa fa-phone"></i>+254 729 990 583</a>
                            </li>
                            <li><a href="mailto:business@oracom.co.ke" target="_blank"><i
                                        class="fa fa-envelope-o"></i>business@oracom.co.ke</a></li>
                            <li><a href="https://www.google.co.ke/maps/place/1%C2%B017'31.6%22S+36%C2%B049'18.8%22E/@-1.2921111,36.8218889,17z"
                                    target="_blank"><i class="fa fa-map-marker"></i> TRV Office Plaza, 7th Floor, Suite 7D,
                                    Muthithi Rd,<br> Westlands. Nairobi – Kenya.</a></li>
                        </ul>
                        <ul class="sm">
                            <li><a href="https://wa.me/254718097171" target="_blank"><i class="fa fa-whatsapp"></i></a></li>
                            <li><a href="http://instagram.com/gs_dynasty07" target="_blank"><i
                                        class="fa fa-instagram"></i></a></li>
                            <li><a href="https://facebook.com/handbagonlineshopp" target="_blank"><i
                                        class="fa fa-facebook"></i></a></li>
                            <li><a href="https://youtube.com/shorts/Q1XSmmlW2j0" target="_blank"><i
                                        class="fa fa-youtube-play"></i></a></li>
                        </ul>
                    </div>
                </div>

                <div class="form-ctn mx-auto">
                    <form class="bg-white px-4 py-5" action="">
                        <div class="h-hr">
                            <h4 class="h">Contact Us</h4>
                            <span class="hr"></span>
                        </div>
                        <div class="">
                            <div class="">
                                <div class="field-ctn">
                                    <input type="text" id="name2" class="form-control" required>
                                    <label for="name2">Name</label>
                                </div>
                            </div>
                            <div class="">
                                <div class="field-ctn">
                                    <input type="email" id="name1" class="form-control" required>
                                    <label for="name1">Email</label>
                                </div>
                            </div>
                            <div class="">
                                <div class="field-ctn">
                                    <textarea name="message" class="form-control" id="msg" required></textarea>
                                    <label for="name2">Message</label>
                                </div>
                            </div>

                        </div>
                        <div class="d-flex align-items-center">
                            <input type="submit" class="btn btn-brand prim text-light d-inline px-4" value="Submit">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block script %}{% endblock %}

flask-oracom-main/OraApp/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    {% include 'mail-styles.html' %}
</head>
<body>
    <div class="ctn">
		<div class="top">
			<div class="logo">
                <h2>Ora<span>Jobs</span></h2>
				<span class="img-ctn"><img src="{{ img }}" alt=""></span>
			</div>
		</div>

		{% if shortlist %}
			<div class="main">
				<h2 class="h2">You are Shortlisted</h2>
				<p>Hello {{ shortlist['Applicant'].l_name }},</p>
				<p>
					We are glad to inform you that you have been shortlisted for a job you applied for at {{ shortlist['Job'].company.name }}.
				</p>
				<p>Application details: </p>
				<table class="tbl">
					<tr>
						<th>Job Applied</th>
						<td>{{ shortlist['Job'].title }}</td>
					</tr>
					<tr>
						<th>Date Applied</th>
						<td>{{ shortlist['date_applied'].strftime("%d %b, %Y") }}</td>
					</tr>
					<tr>
						<th>Job Category</th>
						<td>{{ shortlist['Job'].category }}</td>
					</tr>
					<tr>
						<th>Company</th>
						<td>{{ shortlist['Job'].company.name }}</td>
					</tr>
				</table>

				<p>Selected candidates will be contacted.</p>
				<p>
					Thanks,<br>
					The OraJobs Team.
				</p>
				<p>View more available job vacancies:<br>
				<a href="{{ jobs }}" target="_blank" class="btn" >Find Jobs</a></p>
			</div>
		{% else %}
			<div class="main">
				<h2 class="h2">Password Reset</h2>
				<p>Hello {{ name }},</p>
				<p>
					We heard that you lost your OraJobs password. Sorry about that!
					You can use the following button to reset your password:<br>
					<a href="{{ link }}" target="_blank" class="btn" >Reset Password</a>
				</p>
				<p>This link will expire in 30 minutes. To get a new Password Reset link, visit:
				<a href="{{ resend }}" target="_blank" >Request Password Reset </a></p>
				<p>
					Thanks,<br>
					The OraJobs Team.
				</p>
			</div>
		{% endif %}
		<div class="foot">
			<p class="text-muted m-0"><small>You are receiving this email because you have registered an account with OraJobs.</small></p>
		</div>
	</div>
</body>
</html>

flask-oracom-main/OraApp/templates/forgot_password.html
{% extends 'base.html' %}


{% block container %}
    <section class="hero-form-section bg-light">
        <div class="container-fluid bg-teal-lgrad text-light py-3">
            <h2 class="text-center">Password Reset</h2>
            <div class="d-flex py-3">
                <div class="mx-auto d-sm-flex text-light bg-secondary align-items-center justify-content-between p-3">
                    <div class="me-sm-5">
                        <h4 class="">Forgot Password? </h4>
                        <p class="m-0">
                            Enter your account's verified email address. A password reset link will be sent to your email.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="form-section" class="pb-5 bg-light ">
        <div class="container">
            <div class="d-flex">
                <div class="form-ctn mx-auto">
                    <form class="bg-white px-4 py-5" method="POST" action="">
                        <!-- cross site request forgery token -->
                        {{form.hidden_tag()}}
                        <div class="h-hr">
                            <h4 class="h">Reset Password</h4>
                            <span class="hr"></span>
                        </div>
                        <div class="">
                            <div class="form-group">
                                <div class="field-ctn">
                                    <!-- input validation -->
                                    {% if form.email.errors %}
                                        {{form.email(class="form-control is-invalid")}}
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                                <span>{{error}}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{form.email(class="form-control")}}
                                    {% endif %}
                                    <!-- input label -->
                                    {{form.email.label(class="form-control-label")}}
                                </div>
                            </div>                           
                        </div>
                        <div class="">
                            <!-- submit button  -->
                            {{form.submit(class="btn btn-brand prim text-light d-inline px-4")}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
{% block script %}{% endblock %}

flask-oracom-main/OraApp/templates/job-search.html
<section id=" " class="">
    <div class="container-fluid bg-teal-lgrad text-light text-center py-3">
        <h2 class="m-0">Find Jobs!!!</h2>
        <div class="d-flex py-3">
            <div class="mx-auto text-light bg-secondary px-5 py-3">
                <form class="my-2 search-form" action="{{ url_for('jobs.job_search') }}" method="post">
                    {{ form1.hidden_tag() }}
                    <input type="text" placeholder="Job Title/Category" class="d-block d-sm-inline" name="title" required>
                    <input type="text" name="location" placeholder="Location" class="d-block d-sm-inline my-2 ms-sm-1">
                    <button type="submit" class="btn btn-sm btn-brand peach text-light px-3 d-block d-sm-inline ms-sm-1"> <i class="fa fa-search"></i> Search </button>
                </form>
            </div>
        </div>
    </div>
</section>

flask-oracom-main/OraApp/templates/mail-styles.html
<style type="text/css">
	* {
		margin: 0;
		padding: 0;
		box-sizing: border-box;

	}

	body {
		font-family: sans-serif;
	}
	.tbl {
		width: 100%;
		border: 1px solid rgba(0, 0, 0, 0.15);
		margin-bottom: 20px;
	}

	.tbl tr:nth-child(even){
	    background: #eee;
	}

	.tbl tr td,
	.tbl tr th {
		padding: 5px;
		text-align: left;
		border: 1px solid rgba(0, 0, 0, 0.15);
	}

	.ctn {
		color: #212529;
	}

	.top {
		padding: 8px 16px;
		position: relative;
	}

	.top .logo {
		display: flex;
		height: auto;
		width: 100%;
		align-items: center;
		justify-content: space-between;
		background: linear-gradient(135deg, #f8f9fa 75%, #fab36b 75%);
		border: 1px solid #abc;
		border-radius: 50px;
		padding: 8px 16px;
	}

	.top .img-ctn {
		width: 40px;
		position: relative;
	}

	.top .img-ctn img {
		width: 100%;
		display: block;
	}

	.top h2 span {
		color: #4d91ff;
	}

	.main {
		width: 100%;
		padding: 30px 16px;
	}

	a.btn {
		background: #4d91ff;
		color: #f8f9fa;
		display: inline-block;
		padding: 6px 8px;
		border-radius: 3px;
		border: solid 1px rgba(0, 0, 0, 0.15);
		border-bottom: solid 2px rgba(0, 0, 0, 0.15);
		margin: 8px 0;
	}

	a {
		color: #4d91ff;
		text-decoration: none;
	}

	.h2 {
		text-align: center;
		padding: 8px 0;
		border-bottom: 1px solid rgba(0, 0, 0, 0.15);
	}

	p,
	.h2 {
		margin-bottom: 16px;
	}

	.text-muted {
		color: #6c6d6f;
	}

	

	.ctn .foot {
		width: 100%;
		text-align: center;
		background: #f8f9fa;
		padding: 8px 16px;
		border-top: 1px solid rgba(0, 0, 0, 0.15);
	}

	.m-0 {
		margin: 0;
	}

</style>