flask-oracom-main/OraApp/applicants/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect, request, abort
from OraApp import db, bcrypt
from OraApp.forms import Applicant_User_Update, User_Login, Applicant_Signup, Applicant_User_Update, Forgot_Password, Reset_Password
from OraApp.models import User, Applicant, Job, jobs_applied as applied
from OraApp.utils import save_file, remove_file, user_role_required, send_pwd_reset_email
from flask_login import login_user, current_user


applicant = Blueprint('applicant', __name__)

# Applicant Dashboard
@applicant.route("/applicant/account")
@user_role_required('applicant')
def applicant_account():
    user = current_user.applicants
    jobs = user.applied_jobs
    query = db.session.query(applied).join(Applicant).filter(Applicant.id==user.id).all() 
    shortlists = [ i for i in query if i.shortlisted]

    return render_template("applicants/account.html", title="Applicant | Account", user=user, jobs=jobs, shortlists=shortlists)

# Applicant Account Settings
@applicant.route("/applicant/settings", methods=['GET','POST'])
@user_role_required('applicant')
def settings():
    user = current_user.applicants
    form = Applicant_User_Update()

    if form.validate_on_submit():
        user.f_name = form.f_name.data.strip().capitalize()
        user.l_name = form.l_name.data.strip().capitalize()
        user.user.email = form.email.data.lower()
        user.phone = form.phone.data 

        if form.resume.data:
            new_file = save_file('applicant/resume/', form.resume.data)
            if new_file:
                old_file = f'applicant/resume/{str(user.resume)}'
                try:
                    remove_file(old_file)
                except FileNotFoundError:
                    flash(f'File or Directory not found!', 'danger')
                user.resume = new_file

        if form.image.data:
            img = save_file('applicant/image/', form.image.data)
            if img:
                if user.image != 'anony.png':
                    file = f'applicant/image/{str(user.image)}'
                    remove_file(file)
                user.image = img

        db.session.commit()
        flash(f'Account Updated Successfully.', 'success')
        return redirect(url_for('.settings'))

    form.f_name.data = user.f_name 
    form.l_name.data = user.l_name
    form.email.data = user.user.email
    form.phone.data = user.phone

    return render_template("applicants/settings.html", title="OraJobs | Applicant Settings", form=form, user = user)

@applicant.route("/applicant/application/<int:job_id>")
@user_role_required('applicant')
def apply_for_job(job_id):
    user = current_user.applicants
    job = Job.query.get_or_404(job_id)
    
    user.applied_jobs.append(job)
    db.session.commit()

    flash(f'Application sent Successfully!', 'success')
    return redirect(url_for('.jobs_applied'))

@applicant.route("/applicant/jobs-applied")
@user_role_required('applicant')
def jobs_applied():
    user = current_user.applicants
    page = request.args.get('page', 1, type=int)
    jobs = db.session.query(Job, applied.c.date_applied, applied.c.shortlisted).select_from(Job).join(applied).join(Applicant).filter(Applicant.id==user.id).order_by(applied.c.date_applied.desc()).paginate(page=page, per_page=15)

    return render_template("applicants/jobs.html", title="OraJobs | Applied Jobs", jobs=jobs)

@applicant.route("/applicant/shortlisted-jobs")
@user_role_required('applicant')
def shortlisted_jobs():
    user = current_user.applicants
    jobs = db.session.query(Job).join(applied).join(Applicant).filter((Applicant.id==user.id) & (applied.c.shortlisted)).all() 

    return render_template("applicants/shortlists.html", title="OraJobs | Applied Jobs", jobs=jobs)

@applicant.route("/applicant/<int:job_id>/remove-job/", methods=['POST'])
@user_role_required('applicant')
def remove_job(job_id):
    user = current_user.applicants
    job = Job.query.get_or_404(job_id)
    user.applied_jobs.remove(job)

    db.session.commit()
            
    flash(f'Job removed from the list successfully', 'success')
    return redirect(url_for('.jobs_applied'))

@applicant.route("/applicant/<int:applicant_id>/delete-image", methods=['POST'])
@user_role_required('applicant')
def delete_image(applicant_id):
    user = Applicant.query.get_or_404(applicant_id)
    if not user.user == current_user:
        abort(403)

    if user.image and user.image != "anony.png":
        file = f'applicant/image/{str(user.image)}'
        try:
            remove_file(file)
            user.image = 'anony.png'
            db.session.commit()
            flash(f'Image Removed Successfully!', category='success')
        except FileNotFoundError:
            user.image = 'anony.png'
            db.session.commit()
            flash(f'File not Found!', category='danger')
    
    return redirect(url_for('.settings'))

@applicant.route("/applicant/notifications")
@user_role_required('applicant')
def notifications():
    pass

# Signing in Applicant user
@applicant.route("/applicant/login", methods=['GET', 'POST'])
def applicant_login():
    if current_user.is_authenticated and current_user.applicants:
        return redirect(url_for('.applicant_account'))
    form = User_Login()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.applicants and bcrypt.check_password_hash(user.password, form.password.data):
            match = Applicant.query.filter_by(user_id=user.id).first()
            login_user(user, remember=form.remember.data)
            flash(f'Logged in as {match.l_name}!', 'success')
            return redirect(request.args.get('next') or url_for('.applicant_account'))
        else:
            flash(f'Invalid Email or Password! Please Try Again.', 'danger')
    return render_template("applicants/login.html", title="OraJobs | Applicant Login", form=form)

# Applicant user registration
@applicant.route("/applicant/signup", methods=['POST', 'GET'])
def applicant_signup():
    if current_user.is_authenticated and current_user.applicants:
        return redirect(url_for('.applicant_account'))
    form = Applicant_Signup()
    if form.validate_on_submit():
        resume = save_file('applicant/resume/', form.resume.data)
        pw_hash = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        user = User(email=form.email.data.lower(), user_role='applicant', password=pw_hash)
        db.session.add(user)

        if form.image.data:
            image = save_file('applicant/image/', form.image.data) 
            applicant = Applicant(f_name=form.f_name.data.strip().capitalize(), l_name=form.l_name.data.strip().capitalize(), phone=form.phone.data, resume=resume, image=image, user=user)
            db.session.add(applicant)
            db.session.commit()
        else:
            applicant = Applicant(f_name=form.f_name.data.strip().capitalize(), l_name=form.l_name.data.strip().capitalize(), phone=form.phone.data, resume=resume, user=user)
            db.session.add(applicant)
            db.session.commit()

        flash(f'Account Successfully created for {form.email.data}!', 'success')
        login_user(user, remember=True)
        return redirect(url_for('.settings'))
    return render_template("applicants/signup.html", title="OraJobs | Applicant Signup", form=form)

# Applicant User password reset request
@applicant.route("/applicant/password-reset", methods=['GET', 'POST'])
def password_reset_request():
    if current_user.is_authenticated and current_user.applicants:
        return redirect(url_for('.applicant_account'))
    form = Forgot_Password()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            try:
                send_pwd_reset_email(user, 'applicant', user.applicants.f_name)
                flash('A password reset link has been sent to your email', 'info')
                return redirect(url_for('.applicant_login'))
            except:
                flash('Something went wrong! Please Try Again.', 'warning')
                return redirect(url_for('.password_reset_request'))
        else:
            flash('Email not registered. Send the email you registered your account with.', 'warning')
            return redirect(url_for('.password_reset_request'))
    return render_template("forgot_password.html", title="Applicant | Reset Password", form=form)

# Applicant user password reset token
@applicant.route("/applicant/password-reset/<string:token>", methods=['GET', 'POST'])
def password_reset_link(token):
    if current_user.is_authenticated and current_user.applicants:
        return redirect(url_for('.applicant_account'))
    user = User.verify_reset_token(token)
    if not user:
        flash('The link is either invalid or has expired!', 'warning')
        return redirect(url_for('.password_reset_request'))
          
    form = Reset_Password()
    if form.validate_on_submit():
        pw_hash = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = pw_hash
        db.session.commit()

        flash('Your Password has been updated', 'success')
        return redirect(url_for('.applicant_login'))
    
    return render_template("reset_password.html", title="Applicant | Reset Password", form=form)

flask-oracom-main/OraApp/jobs/routes.py
from OraApp import db
from OraApp.models import Job, jobs_applied, Employer
from flask import render_template, Blueprint, request, abort
from OraApp.forms import Job_Search

jobs = Blueprint('jobs', __name__)

# Job details
@jobs.route("/jobs/<int:job_id>/details/")
def profile(job_id):
    job = Job.query.get_or_404(job_id)
    query = db.session.query(jobs_applied.c.shortlisted).filter_by(job_id=job_id)
    return render_template("jobs/profile.html", title="OraJobs | Job Details", job=job, query=query)

# List of all jobs
@jobs.route("/jobs/")
@jobs.route("/jobs/list/")
def job_list():
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.order_by(Job.date_posted.desc()).paginate(page=page, per_page=15)

    query = db.session.query(Job.category.distinct().label('category'))
    filtered = Job.query
    categories = [row.category for row in query.all()]
    return render_template("jobs/list.html", title="OraJobs | Jobs List", jobs=jobs, filtered=filtered, form1=form1, categories=categories)

@jobs.route("/jobs/categories/")
def categories():
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    query = db.session.query(Job.category.distinct().label('category')).paginate(page=page, per_page=15)
    jobs = Job.query
    categories = [row.category for row in query.items]
    return render_template("jobs/categories.html", title="OraJobs | Jobs Categories", jobs=jobs, form1=form1, categories=categories,pages=query)

# Filter jobs by category
@jobs.route("/jobs/categories/<string:category>")
def filtered(category):
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.filter_by(category=category).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15) or abort(404)
    
    head = f'{category} Jobs'
    return render_template("jobs/filtered.html", title="OraJobs | Jobs List", jobs=jobs, form1=form1, head=head)

# Jobs search
@jobs.route("/jobs/search", methods=['POST'])
def job_search():
    form1 = Job_Search()
    form = request.form
    title_or_category = form['title']
    location = form['location']
    search1 = "%{0}%".format(title_or_category)
    search2 = "%{0}%".format(location)

    page = request.args.get('page', 1, type=int)

    jobs = db.session.query(Job).select_from(Job).filter((Job.title.like(search1) | Job.category.like(search1))).join(Employer).filter(Employer.location.like(search2)).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15) 

    
    locations = f'in "{ location }"' if location else ''
    head = f'Search Results for "{ title_or_category }" {locations}'
    return render_template("jobs/filtered.html", title="OraJobs | Job Search", jobs=jobs, head=head, form1=form1)

flask-oracom-main/OraApp/main/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect
from flask_login import logout_user, current_user

main = Blueprint('main', __name__)

@main.route("/")
def home():
    if current_user.is_authenticated:
        user = current_user.user_role
        return redirect(url_for(f'{user}.{user}_account'))
    return render_template("index.html", title="OraJobs | Home")

@main.route("/about-us")
def about():
    return render_template("about.html", title="OraJobs | About Us")

@main.route("/logout")
def logout():
    logout_user()
    flash(f'Logged Out successfully.', 'primary')
    return redirect(url_for('.home'))

flask-oracom-main/OraApp/templates/applicants/account.html
{% extends 'base.html' %}

{% block container %}

    <section class="py-3 bg-light min-vh">
        <div class="container ">
            <h3 class="text-light prim my-3 p-3">Account Activities</h3>
            <a href="{{ url_for('jobs.job_list') }}" class="btn btn-sm btn-brand peach my-2 text-light">Find Jobs</a>

            <div class="row row-cols-lg-4 row-cols-md-2 row-cols-1 g-2">
                <div class="col">
                    <a href="{{ url_for('applicant.jobs_applied') }}" class="admin-card users-card">
                        <div class ="views">
                            <div class ="no">{{ jobs|length }}</div>
                            <div class ="name">Jobs Applied</div>
                        </div>
                        <div class ="icon-box">
                            <i class="fa fa-paper-plane" aria-hidden="true"></i>
                        </div>
                    </a>
                </div>
                <div class="col">
                    <a href="{{ url_for('applicant.shortlisted_jobs') }}" class="admin-card  users-card">
                        <div class ="views">
                            <div class ="no">{{ shortlists|length }}</div>
                            <div class ="name">Shortlisted Jobs</div>
                        </div>
                        <div class ="icon-box">
                            <i class="fa fa-bookmark" aria-hidden="true"></i>
                        </div>
                    </a>
                </div>
                <!-- <div class="col">
                    <a href="{{ url_for('admin.admin_companies') }}" class="admin-card  users-card">
                        <div class ="views">
                            <div class ="no">5</div>
                            <div class ="name">Notifications</div>
                        </div>
                        <div class ="icon-box">
                            <i class="fa fa-comments" aria-hidden="true"></i>
                        </div>
                    </a>
                </div> -->
                
            </div>
        </div>
    </section>

{% endblock %}
{% block script %}{% endblock %}

flask-oracom-main/OraApp/templates/applicants/jobs.html
{% extends 'base.html' %}

{% block logged_applicant %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Account</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('jobs.job_list')}}">Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('applicant.jobs_applied')}}">Jobs Applied</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.company_list')}}">Companies</a>
    </li>
{% endblock %}

{% block container %}

    <section class="py-3 bg-light min-vh">
        <div class="container ">
            <h3 class="text-light prim my-3 p-3">Applications <i class="fa fa-send" aria-hidden="true"></i></h3>
            <div class="row row-cols-1 g-2">
                <div class="col">
                    <div class="bg-white p-3 border">
                        <div class="d-flex align-items-center">
                            <h4>Jobs Applied: <span class="text-muted">{{ jobs.total or 'No Applications Sent.' }}</span></h4>
                            <a href="{{ url_for('jobs.job_list') }}" class="btn btn-sm ms-auto btn-success my-2 text-light">Find More Jobs</a>
                        </div>
                        {% for job, date, status in jobs.items %}

                            <div class="modal fade" id="remove-job{{job.id}}" tabindex="-1" aria-labelledby="" aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                    <div class="modal-content bg-c-white t-dark">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="">Remove Job from List?</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <form action="{{ url_for('applicant.remove_job', job_id=job.id) }}" method="post">
                                                <input type="submit" class="btn btn-sm btn-danger" value="Remove">
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="d-flex rad-3 border my-3 p-3 align-items-end">
                                <div class="">
                                    <a href="{{ url_for('jobs.profile', job_id=job.id) }}" class="m-0 h3 text-dark">
                                        {{ job.title }}
                                    </a>
                                    <p class="text-muted">
                                        {{ job.company.name.capitalize() }} | <i class="fa fa-map-marker t-prim"></i> {{ job.company.location }}
                                    </p>
                                    <a href="{{ url_for('jobs.profile', job_id=job.id) }}" class="btn btn-brand prim text-light btn-sm">{{ job.type }}</a>
                                    <small class=" ms-2">Applied {{ date.strftime("%d %b, %Y") }}</small>

                                </div>
                                <div class="ms-auto">
                                    {% if status %}
                                        <p class="text-success">Shortlisted</p>
                                    {% else %}
                                        <p class="text-warning">Pending</p>
                                    {% endif %}
                                    <a href="#" class="btn btn-sm btn-danger " data-bs-toggle="modal" data-bs-target="#remove-job{{job.id}}"><span class="d-sm-inline d-none">Remove</span> <i class="fa fa-trash"></i></a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>  
            </div>
            {% if jobs.total > jobs.per_page %}
                {% for page_num in jobs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                    {% if page_num %}
                        {% if jobs.page == page_num %}
                            <a href="{{ url_for('applicant.jobs_applied', page=page_num) }}" class="btn btn-sm btn-primary my-3">{{ page_num }}</a>
                        {% else %}
                            <a href="{{ url_for('applicant.jobs_applied', page=page_num) }}" class="btn btn-sm btn-outline-primary my-3">{{ page_num }}</a>
                        {% endif %}
                    {% else %}
                        ...
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </section>

{% endblock %}
{% block script %}{% endblock %}

flask-oracom-main/OraApp/templates/applicants/login.html
{% extends 'base.html' %}

{% block logged_out %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Home</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('jobs.job_list')}}">Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.company_list')}}">Companies</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.about')}}">About Us</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link ps-sm-auto ps-2 dropdown-toggle active" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Login</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{{url_for('employer.employer_login')}}">Employer</a></li>
            <li><a class="dropdown-item" href="{{url_for('applicant.applicant_login')}}">Applicant</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{{url_for('admin.admin_login')}}">Admin</a></li>
        </ul>
    </li>
{% endblock %}

{% block container %}

    <section class="hero-form-section bg-light">
        <div class="container-fluid prim text-light py-3">
            <h2 class="text-center">Applicant Login</h2>
            <div class="d-flex py-3">
                <div class="mx-auto d-sm-flex text-light bg-secondary align-items-center justify-content-between p-3">
                    <div class="me-sm-5">
                        <h4 class="text-white">Not Registered?</h4>
                        <p class="m-0">Begin your job hunt! Find and apply for job vacancies.</p>
                    </div>
                    <div class="sign-up-btn my-2">
                        <a href="{{url_for('applicant.applicant_signup')}}" class="btn btn-sm btn-brand peach text-light px-4">Log In <i class="fa fa-sign-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="form-section" class="pb-5 bg-light">
        <div class="container">
            <div class="d-flex">
                <div class="form-ctn mx-auto">
                    <form class="bg-white px-4 py-5" method="POST" action="">
                        <!-- cross site request forgery token -->
                        {{form.hidden_tag()}}
                        <div class="h-hr">
                            <h4 class="h">Login</h4>
                            <span class="hr"></span>
                        </div>
                        <div class="">
                            <div class="form-group">
                                <div class="field-ctn">
                                    <!-- input validation -->
                                    {% if form.email.errors %}
                                        {{form.email(class="form-control is-invalid")}}
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                                <span>{{error}}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{form.email(class="form-control")}}
                                    {% endif %}
                                    <!-- input label -->
                                    {{form.email.label(class="form-control-label")}}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="field-ctn">
                                    <!-- input validation -->
                                    {% if form.password.errors %}
                                        {{form.password(class="form-control is-invalid")}}
                                        <div class="invalid-feedback">
                                            {% for error in form.password.errors %}
                                                <span>{{error}}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{form.password(class="form-control")}}
                                    {% endif %}
                                    <!-- input label -->
                                    {{form.password.label(class="form-control-label")}}
                                </div>
                            </div>
                            <div class="form-check">
                                <div class="mb-4">
                                    <!-- Checkbox -->
                                    {{form.remember(class="form-check-input")}}
                                    <!-- Checkbox label -->
                                    {{form.remember.label(class="form-check-label")}}
                                </div>
                            </div>
                        </div>
                        <div class="">
                            <!-- submit button  -->
                            {{form.submit(class="btn btn-brand prim text-light d-inline px-4")}}
                            <small class="">
                                <a class="ms-3 t-prim" href="{{ url_for('applicant.password_reset_request') }}">Forgot Password?</a>
                            </small>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
{% block script %}{% endblock %}

flask-oracom-main/OraApp/templates/applicants/shortlists.html
{% extends 'base.html' %}

{% block logged_applicant %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Account</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('jobs.job_list')}}">Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('applicant.jobs_applied')}}">Jobs Applied</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.company_list')}}">Companies</a>
    </li>
{% endblock %}

{% block container %}

    <section class="py-3 bg-light min-vh">
        <div class="container ">
            {% if jobs %}
                <h4 class="text-light bg-teal-lgrad my-3 p-3">You are Shortlisted in the following Job Positions <i class="fa fa-check-square-o" aria-hidden="true"></i></h4>
            {% else %}
                <h4 class="text-light bg-teal-lgrad my-3 p-3">You are not Listed for any Job Positions Yet</h4>
            {% endif %}
                <div class="row row-cols-1 g-2">
                <div class="col">
                    <div class="bg-white p-3 border">
                        <div class="d-flex align-items-center">
                            <h5>Shortlisted in {{ jobs|length }} Jobs</h5>
                            <a href="{{ url_for('jobs.job_list') }}" class="btn btn-sm ms-auto btn-success my-2 text-light">Find More Jobs</a>
                        </div>
                        {% for job in jobs %}
                            <div class="d-flex rad-3 border my-3 p-3 align-items-end">
                                <div class="">
                                    <a href="{{ url_for('jobs.profile', job_id=job.id) }}" class="m-0 h3 text-dark">
                                        {{ job.title }}
                                    </a>
                                    <p class="text-muted mb-2">
                                        {{ job.company.name.capitalize() }} | <i class="fa fa-map-marker t-prim"></i> {{job.company.location}}
                                    </p>
                                    <p class=" m-0">
                                        {% if job.salary %}
                                            <i class="fa fa-money t-prim"></i> KSh. {{ (job.salary | numberFormat)}}
                                        {% else %}
                                            <i class="fa fa-money t-prim"></i> KSh. Not Specified
                                        {% endif %}
                                    </p>
                                </div>
                                <div class="ms-auto">
                                    <a href="{{ url_for('jobs.profile', job_id=job.id) }}" class="btn btn-brand prim text-light btn-sm">{{ job.type }}</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>  
            </div>
          
        </div>
    </section>

{% endblock %}
{% block script %}{% endblock %}