flask-oracom-main/OraApp/employers/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect, request, abort
from OraApp import db, bcrypt
from OraApp.forms import User_Login, Employer_Signup, Employer_User_Update, Job_Add, Job_Update, Forgot_Password, Reset_Password, Company_Search
from OraApp.models import User, Employer, Job, jobs_applied, Applicant
from OraApp.utils import save_file, user_role_required, remove_file, send_pwd_reset_email, send_shortlist_email
from flask_login import login_user, current_user

employer = Blueprint('employer', __name__)

# Employer dashboard
@employer.route("/employer/account/")
@user_role_required('employer')
def employer_account():
    user = current_user.employers
    job_posts = user.jobs
    applicants = db.session.query(Applicant).select_from(Applicant).join(jobs_applied).join(Job).filter_by(company=user).all()
    listed = db.session.query(Applicant).select_from(Applicant).join(jobs_applied).filter_by(shortlisted=True).join(Job).filter_by(company=user).all() 

    return render_template("employers/account.html", title="Employer | Account", jobs=job_posts, applicants=applicants, listed=listed)

# Employer/company details
@employer.route("/company/<int:company_id>/profile/")
def profile(company_id):
    company = Employer.query.get_or_404(company_id)
    return render_template("employers/profile.html", title="OraJobs | Company Profile", company=company)

# company list
@employer.route("/companies/")
@employer.route("/company/list/")
def company_list():
    form1 = Company_Search()
    page = request.args.get('page', 1, type=int)
    companies = Employer.query.paginate(page=page, per_page=15)
    head = 'List of Companies'
    return render_template("employers/list.html", title="OraJobs | Companies", companies=companies, head=head, form1=form1)

@employer.route("/employer/jobs/<int:job_id>/details/")
@user_role_required('employer')
def job_details(job_id):
    job = Job.query.get_or_404(job_id)
    if not job.company == current_user.employers:
        abort(403)
    applicants = db.session.query(jobs_applied.c.job_id).filter_by(job_id=job_id).all()

    return render_template("employers/job-details.html", title="OraJobs | Job Details", job=job, applicants=applicants)

@employer.route("/employer/posted-jobs")
@user_role_required('employer')
def posted_jobs():
    user = current_user.employers
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.filter_by(company=user).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15)
    list = db.session.query(jobs_applied.c.job_id, jobs_applied.c.applicant_id, jobs_applied.c.shortlisted)

    return render_template("employers/jobs.html", title="OraJobs | Posted Jobs", jobs=jobs, list=list)

# Jobs posting
@employer.route("/employer/post-jobs/", methods=['GET', 'POST'])
@user_role_required('employer')
def post_jobs():
    user = current_user.employers
    form = Job_Add()
    form.company_id.data = user.id
    if form.validate_on_submit():
        salary = form.salary.data if form.salary.data else 0
        job = Job(title=form.title.data.strip(), category=form.category.data, type=form.type.data, description=form.description.data, salary=salary, company=user)
        db.session.add(job)
        db.session.commit()
        
        flash(f'New Job Added Successfully!', 'success')
        return redirect(url_for('.posted_jobs'))
    h = 'New Job'
    return render_template("employers/post_jobs.html", title="Employer | Post Jobs", form=form, h=h)

@employer.route("/employer/jobs/<int:job_id>/update", methods=['GET', 'POST'])
@user_role_required('employer')
def edit_jobs(job_id):
    job = Job.query.get_or_404(job_id)

    if not job.company == current_user.employers:
        abort(403)

    form = Job_Update()
    if form.validate_on_submit():
        job.title = form.title.data.strip()
        job.category = form.category.data.strip()
        job.type = form.type.data 
        job.description = form.description.data
        job.salary = form.salary.data if form.salary.data else 0

        db.session.commit()
        flash(f'Job Updated Successfully.', 'success')
        return redirect(url_for('.posted_jobs'))
  
    form.title.data = job.title 
    form.category.data = job.category
    form.salary.data = job.salary
    form.type.data = job.type
    form.description.data = job.description
    h = 'Update Job'
    return render_template("employers/post_jobs.html", title="Employer | Update Job", form=form, job=job, h=h)

@employer.route("/employer/<int:job_id>/remove-job/", methods=['POST'])
@user_role_required('employer')
def remove_job(job_id):
    job = Job.query.get_or_404(job_id)
    if not job.company == current_user.employers:
        abort(403)

    db.session.delete(job)
    db.session.commit()
            
    flash(f'Job Removed Successfully!', 'success')
    return redirect(url_for('.posted_jobs'))

@employer.route("/employer/applicants/")
@user_role_required('employer')
def applicants():
    user = current_user.employers
    page = request.args.get('page', 1, type=int)

    query = db.session.query(Applicant, Job, jobs_applied.c.shortlisted, jobs_applied.c.date_applied).select_from(Applicant).join(jobs_applied).order_by(jobs_applied.c.date_applied).join(Job).filter_by(company=user).paginate(page=page, per_page=15)

    return render_template("employers/candidates.html", title="Employer | Applicants", applicants=query)

@employer.route("/employer/applicants/<int:job_id>")
@user_role_required('employer')
def applicants_per_job(job_id):
    job = Job.query.get_or_404(job_id)
    page = request.args.get('page', 1, type=int)
    if not job.company == current_user.employers:
        abort(403)
    applicants = db.session.query(Applicant, jobs_applied.c.shortlisted, jobs_applied.c.date_applied).select_from(Applicant).join(jobs_applied).filter_by(job_id=job_id).join(Job).order_by(jobs_applied.c.date_applied).all()

    return render_template("employers/filtered.html", title="OraJobs | Applicants per Job", applicants=applicants, job=job)

@employer.route("/employer/applicants/shortlisted")
@user_role_required('employer')
def listed_applicants():
    user = current_user.employers
    page = request.args.get('page', 1, type=int)

    query = db.session.query(Applicant, Job).select_from(Applicant).join(jobs_applied).filter_by(shortlisted=True).join(Job).filter_by(company=user).paginate(page=page, per_page=15)

    return render_template("employers/listed.html", title="Employer | Shortlists", applicants=query)

@employer.route("/employer/candidates/")
@user_role_required('employer')
def candidates():
    pass

# Sending emails to shortlisted applicants
@employer.route("/employer/send-message/<int:applicant_id>", methods=['GET', 'POST'])
@user_role_required('employer')
def send_message(applicant_id):
    pass

# Listing candidates and Sending email notifications to shortlisted applicants
@employer.route("/employer/list-applicant/<int:job_id>/<int:applicant_id>")
@user_role_required('employer')
def list_applicant(job_id, applicant_id):
    user = current_user.employers
    job = Job.query.get_or_404(job_id)
    applicant = Applicant.query.filter_by(id=applicant_id).first()
    email=User.query.filter_by(id=applicant.user_id).first().email
    if not job.company == user:
        abort(403)

    db.session.query(jobs_applied).filter((jobs_applied.c.job_id==job_id)&(jobs_applied.c.applicant_id==applicant_id)).update(dict(shortlisted = True))
    list = db.session.query(Job, Applicant, jobs_applied.c.date_applied).select_from(Job).join(jobs_applied).join(Applicant).filter((jobs_applied.c.job_id==job_id)&(jobs_applied.c.applicant_id==applicant_id)).first()

    try:
        send_shortlist_email(email, dict(list))
        db.session.commit()

        flash(' Applicant listed Successfully', 'success')
        return redirect(url_for('.listed_applicants'))
    except:
        flash('Something went wrong! Please Try Again.', 'warning')
        return redirect(url_for('.applicants'))

@employer.route("/employer/list-applicant/<int:job_id>/<int:applicant_id>",  methods=['POST'])
@user_role_required('employer')
def unlist_applicant(job_id, applicant_id):
    user = current_user.employers
    job = Job.query.get_or_404(job_id)
    if not job.company == user:
        abort(403)

    db.session.query(jobs_applied).filter((jobs_applied.c.job_id==job_id)&(jobs_applied.c.applicant_id==applicant_id)).update(dict(shortlisted = False))
    db.session.commit()
    flash('Applicant removed from your list Successfully', 'success')

    return redirect(url_for('.listed_applicants'))

@employer.route("/employer/notifications/")
@user_role_required('employer')
def notifications():
    pass # pass statement is a placeholder & it does not provide any value to the client

# employer account settings
@employer.route("/employer/settings/", methods=['GET', 'POST'])
@user_role_required('employer')
def settings():
    user = current_user.employers
    form = Employer_User_Update()

    if form.validate_on_submit():
        user.name = form.name.data.strip().upper()
        user.user.email = form.email.data.lower()
        user.phone = form.phone.data 
        user.location = form.location.data 
        user.tagline = form.tagline.data 
        user.description = form.description.data 
        user.website = form.website.data 

        if form.logo.data:
            new_file = save_file('employer/logo/', form.logo.data)
            if new_file:
                if user.logo != 'company.png':
                    old_file = f'employer/logo/{str(user.logo)}'
                    remove_file(old_file)
                
                user.logo = new_file

        db.session.commit()
        flash(f'Account Updated Successfully.', 'success')
        return redirect(url_for('.settings'))
  
    form.name.data = user.name 
    form.email.data = user.user.email
    form.phone.data = user.phone
    form.location.data = user.location
    form.tagline.data = user.tagline

flask-oracom-main/OraApp/jobs/routes.py
from OraApp import db
from OraApp.models import Job, jobs_applied, Employer
from flask import render_template, Blueprint, request, abort
from OraApp.forms import Job_Search

jobs = Blueprint('jobs', __name__)

# Job details
@jobs.route("/jobs/<int:job_id>/details/")
def profile(job_id):
    job = Job.query.get_or_404(job_id)
    query = db.session.query(jobs_applied.c.shortlisted).filter_by(job_id=job_id)
    return render_template("jobs/profile.html", title="OraJobs | Job Details", job=job, query=query)

# List of all jobs
@jobs.route("/jobs/")
@jobs.route("/jobs/list/")
def job_list():
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.order_by(Job.date_posted.desc()).paginate(page=page, per_page=15)

    query = db.session.query(Job.category.distinct().label('category'))
    filtered = Job.query
    categories = [row.category for row in query.all()]
    return render_template("jobs/list.html", title="OraJobs | Jobs List", jobs=jobs, filtered=filtered, form1=form1, categories=categories)

@jobs.route("/jobs/categories/")
def categories():
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    query = db.session.query(Job.category.distinct().label('category')).paginate(page=page, per_page=15)
    jobs = Job.query
    categories = [row.category for row in query.items]
    return render_template("jobs/categories.html", title="OraJobs | Jobs Categories", jobs=jobs, form1=form1, categories=categories,pages=query)

# Filter jobs by category
@jobs.route("/jobs/categories/<string:category>")
def filtered(category):
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.filter_by(category=category).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15) or abort(404)
    
    head = f'{category} Jobs'
    return render_template("jobs/filtered.html", title="OraJobs | Jobs List", jobs=jobs, form1=form1, head=head)

# Jobs search
@jobs.route("/jobs/search", methods=['POST'])
def job_search():
    form1 = Job_Search()
    form = request.form
    title_or_category = form['title']
    location = form['location']
    search1 = "%{0}%".format(title_or_category)
    search2 = "%{0}%".format(location)

    page = request.args.get('page', 1, type=int)

    jobs = db.session.query(Job).select_from(Job).filter((Job.title.like(search1) | Job.category.like(search1))).join(Employer).filter(Employer.location.like(search2)).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15) 

    
    locations = f'in "{ location }"' if location else ''
    head = f'Search Results for "{ title_or_category }" {locations}'
    return render_template("jobs/filtered.html", title="OraJobs | Job Search", jobs=jobs, head=head, form1=form1)

flask-oracom-main/OraApp/main/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect
from flask_login import logout_user, current_user

main = Blueprint('main', __name__)

@main.route("/")
def home():
    if current_user.is_authenticated:
        user = current_user.user_role
        return redirect(url_for(f'{user}.{user}_account'))
    return render_template("index.html", title="OraJobs | Home")

@main.route("/about-us")
def about():
    return render_template("about.html", title="OraJobs | About Us")

@main.route("/logout")
def logout():
    logout_user()
    flash(f'Logged Out successfully.', 'primary')
    return redirect(url_for('.home'))

flask-oracom-main/OraApp/templates/employers/account.html
{% extends 'base.html' %}

{% block container %}

    <section class="py-3 bg-light min-vh">
        <div class="container ">
            <h3 class="text-light bg-teal-lgrad my-3 p-3">Account Activities</h3>
            <a href="{{ url_for('employer.post_jobs') }}" class="btn btn-sm btn-brand peach my-2 text-light">Post Jobs <i class="fa fa-paper-plane" aria-hidden="true"></i></a>

            <div class="row row-cols-lg-4 row-cols-md-2 row-cols-1 g-2">
                <div class="col">
                    <a href="{{ url_for('employer.posted_jobs') }}" class="admin-card users-card">
                        <div class ="views">
                            <div class ="no"> {{ jobs|length }} </div>
                            <div class ="name">Posted Jobs</div>
                        </div>
                        <div class ="icon-box">
                            <i class="fa fa-thumb-tack" aria-hidden="true"></i>
                        </div>
                    </a>
                </div>
                <div class="col">
                    <a href="{{ url_for('employer.applicants') }}" class="admin-card  users-card">
                        <div class ="views">
                            <div class ="no">{{ applicants|length }}</div>
                            <div class ="name">Applicants</div>
                        </div>
                        <div class ="icon-box">
                            <i class="fa fa-users" aria-hidden="true"></i>
                        </div>
                    </a>
                </div>
                <div class="col">
                    <a href="{{ url_for('employer.listed_applicants') }}" class="admin-card  users-card">
                        <div class ="views">
                            <div class ="no">{{ listed|length }}</div>
                            <div class ="name">Shortlisted Applicants</div>
                        </div>
                        <div class ="icon-box">
                            <i class="fa fa-check-square-o" aria-hidden="true"></i>
                        </div>
                    </a>
                </div>
                <!-- <div class="col">
                    <a href="#" class="admin-card  users-card">
                        <div class ="views">
                            <div class ="no">5</div>
                            <div class ="name">Notifications</div>
                        </div>
                        <div class ="icon-box">
                            <i class="fa fa-comments" aria-hidden="true"></i>
                        </div>
                    </a>
                </div> -->
                
            </div>
        </div>
    </section>

{% endblock %}
{% block script %}{% endblock %}

flask-oracom-main/OraApp/templates/employers/candidates.html
{% extends 'base.html' %}

{% block logged_employer %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Account</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.posted_jobs')}}">Your Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('employer.applicants')}}">Applicants</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.post_jobs')}}">Add Jobs</a>
    </li>
{% endblock %} 

{% block container %}

    <section class="py-3 bg-light min-vh">
        <div class="container ">
            <h3 class="text-light bg-teal-lgrad my-3 p-3">Applicants <i class="fa fa-users" aria-hidden="true"></i></h3>
            <div class="row row-cols-1 g-2">
                <div class="col">
                    <div class="bg-white p-3 border">
                        <div class="d-sm-flex d-block align-items-center">
                            <h3>Received Applications: <span class="text-muted">{{ applicants.total }}</span></h3>
                            <a href="{{ url_for('employer.post_jobs') }}" class="btn btn-sm ms-auto btn-outline-success">Add Jobs <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                        </div>
                        {% for user, job, listed, date in applicants.items %}

                            <div class="modal fade" id="text-user{{user.id}}" tabindex="-1" aria-labelledby="" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content bg-c-white t-dark">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="">Send Message</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body py-5">
                                            <form action="{{ url_for('employer.send_message', applicant_id=user.id) }}" method="post">
                                              <div class="mb-3">
                                                <label for="subject" class="col-form-label">Subject:</label>
                                                <input type="text" class="form-control" id="subject">
                                              </div>
                                              <div class="mb-3">
                                                <label for="message-text" class="col-form-label">Message:</label>
                                                <textarea class="form-control" id="message-text"></textarea>
                                              </div>
                                              <button type="submit" class="btn btn-sm btn-primary mb-4 px-3">Send <i class="fa fa-send"></i></button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="d-flex rad-3 border my-3 p-3">
                                <div class="prof-update">
                                    <div class="d-flex">
                                        <div class="profile-img-ctn prof-sm">
                                            <img src="{{ url_for('static', filename='applicant/image/' + user.image) }}" alt="">
                                        </div>
                                        <div class="ms-2">
                                            <p class="m-0 text-bold">{{ user.l_name }} {{ user.f_name }}</p>
                                            <p class="m-0 text-muted">
                                                <a href="mailto:{{ user.user.email }}" target="_blank" class="text-dark text-muted"><i class="fa fa-envelope-o t-prim"></i> {{ user.user.email }}</a>
                                            </p>
                                            <p class="text-muted">
                                                <a href="tel:{{ user.phone }}" target="_blank" class="text-dark text-muted"><i class="fa fa-phone t-prim"></i> {{ user.phone }}</a>
                                            </p>
                                            <p class="">
                                                Applied for 
                                                <a href="{{ url_for('employer.job_details', job_id=job.id) }}" class=""> 
                                                    {{ job.title }}
                                                </a>
                                                <small class="">{{ date.strftime("%d %b, %Y") }}</small>
                                            </p>
                                            <button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#text-user{{user.id}}" >Message <i class="fa fa-send"></i></button>
                                            {% if not listed %}
                                                <a href="{{ url_for('employer.list_applicant', applicant_id=user.id, job_id=job.id) }}" class="btn btn-sm btn-success">
                                                    Shortlist <i class="fa fa-user-plus"></i>
                                                </a>
                                            {% else %}
                                                <button class="btn btn-sm btn-success disabled" >Listed <i class="fa fa-check-square-o"></i></button>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="ms-auto">
                                    <a class="paper  text-dark " href="{{ url_for('static', filename='applicant/resume/' + user.resume) }}" target="_blank">
                                        <img src="{{ url_for('static', filename='img/paper.png') }}">
                                    </a>
                                    <p class="text-center m-0"><small>Resume</small></p> 
                                </div>
                                
                            </div>
                        {% endfor %}
                        {% if applicants.total > applicants.per_page %}
                            {% for page_num in applicants.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                                {% if page_num %}
                                    {% if applicants.page == page_num %}
                                        <a href="{{ url_for('employer.applicants', page=page_num) }}" class="btn btn-sm btn-primary my-3">{{ page_num }}</a>
                                    {% else %}
                                        <a href="{{ url_for('employer.applicants', page=page_num) }}" class="btn btn-sm btn-outline-primary my-3">{{ page_num }}</a>
                                    {% endif %}
                                {% else %}
                                    ...
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>  
            </div>
           
        </div>
    </section>

{% endblock %}
{% block script %}{% endblock %}

flask-oracom-main/OraApp/templates/employers/jobs.html
{% extends 'base.html' %}

{% block logged_employer %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Account</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('employer.posted_jobs')}}">Your Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.applicants')}}">Applicants</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.post_jobs')}}">Add Jobs</a>
    </li>
{% endblock %} 

{% block container %}

    <section class="py-3 bg-light min-vh">
        <div class="container ">
            <h3 class="text-light bg-teal-lgrad my-3 p-3">Posted Jobs <i class="fa fa-thumb-tack" aria-hidden="true"></i></h3>
            <div class="row row-cols-1 g-2">
                <div class="col">
                    <div class="bg-white p-3 border">
                        <div class="d-flex align-items-center">
                            <h4>Your Jobs: <span class="text-muted">{{ jobs.items | length or 'No Posted Jobs Yet.' }}</span></h4>
                            <a href="{{ url_for('employer.post_jobs') }}" class="btn btn-sm ms-auto btn-success my-2 text-light">Add New Job</a>
                        </div>
                        {% for job in jobs.items %}

                            <div class="modal fade" id="remove-job{{job.id}}" tabindex="-1" aria-labelledby="" aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                    <div class="modal-content bg-c-white t-dark">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="">Delete Job?</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <form action="{{ url_for('employer.remove_job', job_id=job.id) }}" method="post">
                                                <input type="submit" class="btn btn-sm btn-danger" value="Remove">
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="d-flex rad-3 border my-3 p-3 align-items-end">
                                <div class="">
                                    <a href="{{ url_for('employer.job_details', job_id=job.id) }}" class="m-0 h3 text-dark">
                                        {{ job.title }}
                                    </a>
                                    <p class="text-muted mb-2">
                                        {{ job.category }} | <a href="{{ url_for('employer.job_details', job_id=job.id) }}" class="btn btn-brand prim text-light btn-sm p-0 px-2">{{ job.type }}</a>
                                    </p>
                                    <p class=" m-0">
                                        {% if job.salary %}
                                            <span><i class="fa fa-money t-prim"></i> KSh. {{ job.salary | numberFormat}}</span>
                                        {% else %}
                                            <span><i class="fa fa-money t-prim"></i> KSh. Not Specified</span>
                                        {% endif %}
                                    </p>
                                </div>
                                <div class="ms-auto">
                                        {% if list.filter_by(job_id=job.id).all()|length %}
                                            {% if list.filter_by(job_id=job.id).all()|length > 1 %}
                                                <p class="text-primary">
                                                    <a href="{{ url_for('employer.applicants_per_job', job_id=job.id) }}" class=""> 
                                                        {{ list.filter_by(job_id=job.id).all()|length }} Applicants
                                                    </a>
                                                </p>
                                            {% else %}
                                                <p class="text-primary">
                                                    <a href="{{ url_for('employer.applicants_per_job', job_id=job.id) }}" class=""> 
                                                        {{ list.filter_by(job_id=job.id).all()|length }} Applicant
                                                    </a>
                                                </p>
                                            {% endif %}
                                        {% else %}
                                            <p class="text-muted"> No Applicants </p>
                                        {% endif %}
                                    
                                    <a href="{{ url_for('employer.edit_jobs', job_id=job.id) }}" class="btn btn-sm btn-warning"><span class="d-sm-inline d-none">Update</span> <i class="fa fa-pencil"></i></a>
                                    <a href="#" class="btn btn-sm btn-danger " data-bs-toggle="modal" data-bs-target="#remove-job{{job.id}}"><span class="d-sm-inline d-none">Remove</span> <i class="fa fa-trash"></i></a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>  
            </div>
            {% if jobs.total > jobs.per_page %}
                {% for page_num in jobs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                    {% if page_num %}
                        {% if jobs.page == page_num %}
                            <a href="{{ url_for('employer.posted_jobs', page=page_num) }}" class="btn btn-sm btn-primary my-3">{{ page_num }}</a>
                        {% else %}
                            <a href="{{ url_for('employer.posted_jobs', page=page_num) }}" class="btn btn-sm btn-outline-primary my-3">{{ page_num }}</a>
                        {% endif %}
                    {% else %}
                        ...
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </section>

{% endblock %}
{% block script %}{% endblock %}