flask-oracom-main/OraApp/employers/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect, request, abort
from OraApp import db, bcrypt
from OraApp.forms import User_Login, Employer_Signup, Employer_User_Update, Job_Add, Job_Update, Forgot_Password, Reset_Password, Company_Search
from OraApp.models import User, Employer, Job, jobs_applied, Applicant
from OraApp.utils import save_file, user_role_required, remove_file, send_pwd_reset_email, send_shortlist_email
from flask_login import login_user, current_user

employer = Blueprint('employer', __name__)

# Employer dashboard
@employer.route("/employer/account/")
@user_role_required('employer')
def employer_account():
    user = current_user.employers
    job_posts = user.jobs
    applicants = db.session.query(Applicant).select_from(Applicant).join(jobs_applied).join(Job).filter_by(company=user).all()
    listed = db.session.query(Applicant).select_from(Applicant).join(jobs_applied).filter_by(shortlisted=True).join(Job).filter_by(company=user).all() 

    return render_template("employers/account.html", title="Employer | Account", jobs=job_posts, applicants=applicants, listed=listed)

# Employer/company details
@employer.route("/company/<int:company_id>/profile/")
def profile(company_id):
    company = Employer.query.get_or_404(company_id)
    return render_template("employers/profile.html", title="OraJobs | Company Profile", company=company)

# company list
@employer.route("/companies/")
@employer.route("/company/list/")
def company_list():
    form1 = Company_Search()
    page = request.args.get('page', 1, type=int)
    companies = Employer.query.paginate(page=page, per_page=15)
    head = 'List of Companies'
    return render_template("employers/list.html", title="OraJobs | Companies", companies=companies, head=head, form1=form1)

@employer.route("/employer/jobs/<int:job_id>/details/")
@user_role_required('employer')
def job_details(job_id):
    job = Job.query.get_or_404(job_id)
    if not job.company == current_user.employers:
        abort(403)
    applicants = db.session.query(jobs_applied.c.job_id).filter_by(job_id=job_id).all()

    return render_template("employers/job-details.html", title="OraJobs | Job Details", job=job, applicants=applicants)

@employer.route("/employer/posted-jobs")
@user_role_required('employer')
def posted_jobs():
    user = current_user.employers
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.filter_by(company=user).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15)
    list = db.session.query(jobs_applied.c.job_id, jobs_applied.c.applicant_id, jobs_applied.c.shortlisted)

    return render_template("employers/jobs.html", title="OraJobs | Posted Jobs", jobs=jobs, list=list)

# Jobs posting
@employer.route("/employer/post-jobs/", methods=['GET', 'POST'])
@user_role_required('employer')
def post_jobs():
    user = current_user.employers
    form = Job_Add()
    form.company_id.data = user.id
    if form.validate_on_submit():
        salary = form.salary.data if form.salary.data else 0
        job = Job(title=form.title.data.strip(), category=form.category.data, type=form.type.data, description=form.description.data, salary=salary, company=user)
        db.session.add(job)
        db.session.commit()
        
        flash(f'New Job Added Successfully!', 'success')
        return redirect(url_for('.posted_jobs'))
    h = 'New Job'
    return render_template("employers/post_jobs.html", title="Employer | Post Jobs", form=form, h=h)

@employer.route("/employer/jobs/<int:job_id>/update", methods=['GET', 'POST'])
@user_role_required('employer')
def edit_jobs(job_id):
    job = Job.query.get_or_404(job_id)

    if not job.company == current_user.employers:
        abort(403)

    form = Job_Update()
    if form.validate_on_submit():
        job.title = form.title.data.strip()
        job.category = form.category.data.strip()
        job.type = form.type.data 
        job.description = form.description.data
        job.salary = form.salary.data if form.salary.data else 0

        db.session.commit()
        flash(f'Job Updated Successfully.', 'success')
        return redirect(url_for('.posted_jobs'))
  
    form.title.data = job.title 
    form.category.data = job.category
    form.salary.data = job.salary
    form.type.data = job.type
    form.description.data = job.description
    h = 'Update Job'
    return render_template("employers/post_jobs.html", title="Employer | Update Job", form=form, job=job, h=h)

@employer.route("/employer/<int:job_id>/remove-job/", methods=['POST'])
@user_role_required('employer')
def remove_job(job_id):
    job = Job.query.get_or_404(job_id)
    if not job.company == current_user.employers:
        abort(403)

    db.session.delete(job)
    db.session.commit()
            
    flash(f'Job Removed Successfully!', 'success')
    return redirect(url_for('.posted_jobs'))

@employer.route("/employer/applicants/")
@user_role_required('employer')
def applicants():
    user = current_user.employers
    page = request.args.get('page', 1, type=int)

    query = db.session.query(Applicant, Job, jobs_applied.c.shortlisted, jobs_applied.c.date_applied).select_from(Applicant).join(jobs_applied).order_by(jobs_applied.c.date_applied).join(Job).filter_by(company=user).paginate(page=page, per_page=15)

    return render_template("employers/candidates.html", title="Employer | Applicants", applicants=query)

@employer.route("/employer/applicants/<int:job_id>")
@user_role_required('employer')
def applicants_per_job(job_id):
    job = Job.query.get_or_404(job_id)
    page = request.args.get('page', 1, type=int)
    if not job.company == current_user.employers:
        abort(403)
    applicants = db.session.query(Applicant, jobs_applied.c.shortlisted, jobs_applied.c.date_applied).select_from(Applicant).join(jobs_applied).filter_by(job_id=job_id).join(Job).order_by(jobs_applied.c.date_applied).all()

    return render_template("employers/filtered.html", title="OraJobs | Applicants per Job", applicants=applicants, job=job)

@employer.route("/employer/applicants/shortlisted")
@user_role_required('employer')
def listed_applicants():
    user = current_user.employers
    page = request.args.get('page', 1, type=int)

    query = db.session.query(Applicant, Job).select_from(Applicant).join(jobs_applied).filter_by(shortlisted=True).join(Job).filter_by(company=user).paginate(page=page, per_page=15)

    return render_template("employers/listed.html", title="Employer | Shortlists", applicants=query)

@employer.route("/employer/candidates/")
@user_role_required('employer')
def candidates():
    pass

# Sending emails to shortlisted applicants
@employer.route("/employer/send-message/<int:applicant_id>", methods=['GET', 'POST'])
@user_role_required('employer')
def send_message(applicant_id):
    pass

# Listing candidates and Sending email notifications to shortlisted applicants
@employer.route("/employer/list-applicant/<int:job_id>/<int:applicant_id>")
@user_role_required('employer')
def list_applicant(job_id, applicant_id):
    user = current_user.employers
    job = Job.query.get_or_404(job_id)
    applicant = Applicant.query.filter_by(id=applicant_id).first()
    email=User.query.filter_by(id=applicant.user_id).first().email
    if not job.company == user:
        abort(403)

    db.session.query(jobs_applied).filter((jobs_applied.c.job_id==job_id)&(jobs_applied.c.applicant_id==applicant_id)).update(dict(shortlisted = True))
    list = db.session.query(Job, Applicant, jobs_applied.c.date_applied).select_from(Job).join(jobs_applied).join(Applicant).filter((jobs_applied.c.job_id==job_id)&(jobs_applied.c.applicant_id==applicant_id)).first()

    try:
        send_shortlist_email(email, dict(list))
        db.session.commit()

        flash(' Applicant listed Successfully', 'success')
        return redirect(url_for('.listed_applicants'))
    except:
        flash('Something went wrong! Please Try Again.', 'warning')
        return redirect(url_for('.applicants'))

@employer.route("/employer/list-applicant/<int:job_id>/<int:applicant_id>",  methods=['POST'])
@user_role_required('employer')
def unlist_applicant(job_id, applicant_id):
    user = current_user.employers
    job = Job.query.get_or_404(job_id)
    if not job.company == user:
        abort(403)

    db.session.query(jobs_applied).filter((jobs_applied.c.job_id==job_id)&(jobs_applied.c.applicant_id==applicant_id)).update(dict(shortlisted = False))
    db.session.commit()
    flash('Applicant removed from your list Successfully', 'success')

    return redirect(url_for('.listed_applicants'))

@employer.route("/employer/notifications/")
@user_role_required('employer')
def notifications():
    pass # pass statement is a placeholder & it does not provide any value to the client

# employer account settings
@employer.route("/employer/settings/", methods=['GET', 'POST'])
@user_role_required('employer')
def settings():
    user = current_user.employers
    form = Employer_User_Update()

    if form.validate_on_submit():
        user.name = form.name.data.strip().upper()
        user.user.email = form.email.data.lower()
        user.phone = form.phone.data 
        user.location = form.location.data 
        user.tagline = form.tagline.data 
        user.description = form.description.data 
        user.website = form.website.data 

        if form.logo.data:
            new_file = save_file('employer/logo/', form.logo.data)
            if new_file:
                if user.logo != 'company.png':
                    old_file = f'employer/logo/{str(user.logo)}'
                    remove_file(old_file)
                
                user.logo = new_file

        db.session.commit()
        flash(f'Account Updated Successfully.', 'success')
        return redirect(url_for('.settings'))
  
    form.name.data = user.name 
    form.email.data = user.user.email
    form.phone.data = user.phone
    form.location.data = user.location
    form.tagline.data = user.tagline

flask-oracom-main/OraApp/jobs/routes.py
from OraApp import db
from OraApp.models import Job, jobs_applied, Employer
from flask import render_template, Blueprint, request, abort
from OraApp.forms import Job_Search

jobs = Blueprint('jobs', __name__)

# Job details
@jobs.route("/jobs/<int:job_id>/details/")
def profile(job_id):
    job = Job.query.get_or_404(job_id)
    query = db.session.query(jobs_applied.c.shortlisted).filter_by(job_id=job_id)
    return render_template("jobs/profile.html", title="OraJobs | Job Details", job=job, query=query)

# List of all jobs
@jobs.route("/jobs/")
@jobs.route("/jobs/list/")
def job_list():
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.order_by(Job.date_posted.desc()).paginate(page=page, per_page=15)

    query = db.session.query(Job.category.distinct().label('category'))
    filtered = Job.query
    categories = [row.category for row in query.all()]
    return render_template("jobs/list.html", title="OraJobs | Jobs List", jobs=jobs, filtered=filtered, form1=form1, categories=categories)

@jobs.route("/jobs/categories/")
def categories():
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    query = db.session.query(Job.category.distinct().label('category')).paginate(page=page, per_page=15)
    jobs = Job.query
    categories = [row.category for row in query.items]
    return render_template("jobs/categories.html", title="OraJobs | Jobs Categories", jobs=jobs, form1=form1, categories=categories,pages=query)

# Filter jobs by category
@jobs.route("/jobs/categories/<string:category>")
def filtered(category):
    form1 = Job_Search()
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.filter_by(category=category).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15) or abort(404)
    
    head = f'{category} Jobs'
    return render_template("jobs/filtered.html", title="OraJobs | Jobs List", jobs=jobs, form1=form1, head=head)

# Jobs search
@jobs.route("/jobs/search", methods=['POST'])
def job_search():
    form1 = Job_Search()
    form = request.form
    title_or_category = form['title']
    location = form['location']
    search1 = "%{0}%".format(title_or_category)
    search2 = "%{0}%".format(location)

    page = request.args.get('page', 1, type=int)

    jobs = db.session.query(Job).select_from(Job).filter((Job.title.like(search1) | Job.category.like(search1))).join(Employer).filter(Employer.location.like(search2)).order_by(Job.date_posted.desc()).paginate(page=page, per_page=15) 

    
    locations = f'in "{ location }"' if location else ''
    head = f'Search Results for "{ title_or_category }" {locations}'
    return render_template("jobs/filtered.html", title="OraJobs | Job Search", jobs=jobs, head=head, form1=form1)

flask-oracom-main/OraApp/main/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect
from flask_login import logout_user, current_user

main = Blueprint('main', __name__)

@main.route("/")
def home():
    if current_user.is_authenticated:
        user = current_user.user_role
        return redirect(url_for(f'{user}.{user}_account'))
    return render_template("index.html", title="OraJobs | Home")

@main.route("/about-us")
def about():
    return render_template("about.html", title="OraJobs | About Us")

@main.route("/logout")
def logout():
    logout_user()
    flash(f'Logged Out successfully.', 'primary')
    return redirect(url_for('.home'))

flask-oracom-main/OraApp/templates/jobs/categories.html
{% extends 'base.html' %}

{% block logged_applicant %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Account</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('jobs.job_list')}}">Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('applicant.jobs_applied')}}">Jobs Applied</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.company_list')}}">Companies</a>
    </li>
{% endblock %}
                          
{% block logged_out %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Home</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('jobs.job_list')}}">Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.company_list')}}">Companies</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.about')}}">About Us</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link ps-sm-auto ps-2 dropdown-toggle" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Login</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{{url_for('employer.employer_login')}}">Employer</a></li>
            <li><a class="dropdown-item" href="{{url_for('applicant.applicant_login')}}">Applicant</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{{url_for('admin.admin_login')}}">Admin</a></li>
        </ul>
    </li>
{% endblock %}

{% block container %}

{% include 'job-search.html' %}

<section id="job-categories" class="bg-light py-5">
    <div class="container">
        <div class="p-3 mb-2 d-flex align-items-center">
            <p class="h2">Top Job Categories</p>
        </div> 
        <div class="row row-cols-xl-4 row-cols-lg-3 row-cols-md-2 row-cols-1 g-2">
            {% if categories %}
                {% for category in categories %}
                    <div class="col">
                        <a href="{{ url_for('jobs.filtered', category=category) }}" class="admin-card category-card bg-white border d-block p-3 ">
                            <p class="h6"><i class="fa fa-tags me-2 t-prim"></i> {{category}}</p>
                            <div class="category-img-box">
                                <div class ="image-box my-3">
                                    <img class="rounded-circle" src="{{url_for('static', filename='img/job_search.png')}}" alt="">
                                </div>
                                
                                <div class ="views">
                                    <p class="h5 m-0 p-0">{{ jobs.filter_by(category=category).all() | length
                                    }}</p>
                                    <small class="text-muted p-0 m-0" >Total Jobs</small>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            {% else %}
                <p>No available Job Categories</p>
            {% endif %}
        </div>
        {% if pages.total > pages.per_page %}
            {% for page_num in pages.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if pages.page == page_num %}
                        <a href="{{ url_for('jobs.categories', page=page_num) }}" class="btn btn-sm btn-primary my-3">{{ page_num }}</a>
                    {% else %}
                        <a href="{{ url_for('jobs.categories', page=page_num) }}" class="btn btn-sm btn-outline-primary my-3">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</section>

{% endblock %}
{% block script %}{% endblock %}

flask-oracom-main/OraApp/templates/jobs/filtered.html
{% extends 'base.html' %}

{% block logged_applicant %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Account</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('jobs.job_list')}}">Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('applicant.jobs_applied')}}">Jobs Applied</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.company_list')}}">Companies</a>
    </li>
{% endblock %}
                          
{% block logged_out %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Home</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('jobs.job_list')}}">Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.company_list')}}">Companies</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.about')}}">About Us</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link ps-sm-auto ps-2 dropdown-toggle" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Login</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{{url_for('employer.employer_login')}}">Employer</a></li>
            <li><a class="dropdown-item" href="{{url_for('applicant.applicant_login')}}">Applicant</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{{url_for('admin.admin_login')}}">Admin</a></li>
        </ul>
    </li>
{% endblock %}

{% block container %}

{% include 'job-search.html' %}

<section id="jobs-list" class="bg-light py-5">
    <div class="container">
        <div class="section-header">
            <h2 class="">{{ head }}: <span class="text-muted">{{ jobs.total }}</span></h2>
        </div>
        
        <div class="row row-cols-lg-3 row-cols-md-2 row-cols-1 g-2">
            {% if jobs %}
                {% for job in jobs.items %}
                    <div class="col">
                        <div class="bg-white border p-3 jobs-card h-100">
                            <div class="d-flex">
                                <div class="">
                                    <a href="{{ url_for('employer.profile', company_id=job.company.id) }}" class="profile-img-ctn prof-sm">
                                        <img src="{{ url_for('static', filename='employer/logo/' + job.company.logo) }}" alt="">
                                    </a>
                                </div>
                                <div class="w-100 ms-2">
                                    <div class="border-bottom d-flex align-items-center">
                                        <small class="text-muted"><i class="fa fa-calendar t-prim"></i> {{ job.date_posted.strftime("%d %b, %Y") }}</small>

                                        {% if current_user.is_authenticated and current_user.applicants and job in current_user.applicants.applied_jobs %}
                                            <span class="text-success ms-auto">Applied <i class="fa fa-check-square-o"></i></span>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="">
                                <h3 class="d-block text-dark m-0">{{ job.title }}</h3>
                                <p class="text-muted"><i class="fa fa-map-marker t-prim"></i> {{ job.company.location }}</p>
                                <p class="d-flex m-0 align-items-end">
                                    {% if job.salary %}
                                        <small>
                                            <i class="fa fa-money t-prim"></i> KSh. {{ (job.salary | numberFormat)}}
                                        </small>
                                    {% else %}
                                        <small>
                                            <i class="fa fa-money t-prim"></i> KSh. Not Specified
                                        </small>
                                    {% endif %}
                                    <a href="{{ url_for('jobs.profile', job_id=job.id) }}" class="btn btn-sm btn-brand prim text-light ms-auto">{{ job.type }}</a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No Posted Jobs yet. Check later.</p>
            {% endif %}
        </div>
        {% if jobs.total > jobs.per_page %}
            {% for page_num in jobs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if jobs.page == page_num %}
                        <a href="{{ url_for('jobs.filtered', category=jobs.items[0].category, page=page_num) }}" class="btn btn-sm btn-primary my-3">{{ page_num }}</a>
                    {% else %}
                        <a href="{{ url_for('jobs.filtered', category=jobs.items[0].category, page=page_num) }}" class="btn btn-sm btn-outline-primary my-3">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</section>

{% endblock %}
{% block script %}{% endblock %}

flask-oracom-main/OraApp/templates/jobs/list.html
{% extends 'base.html' %}

{% block logged_applicant %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Account</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('jobs.job_list')}}">Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('applicant.jobs_applied')}}">Jobs Applied</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.company_list')}}">Companies</a>
    </li>
{% endblock %}
                          
{% block logged_out %}
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.home')}}">Home</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2 active" href="{{url_for('jobs.job_list')}}">Jobs</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('employer.company_list')}}">Companies</a>
    </li>
    <li>
        <a class="nav-link ps-sm-auto ps-2" href="{{url_for('main.about')}}">About Us</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link ps-sm-auto ps-2 dropdown-toggle" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Login</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{{url_for('employer.employer_login')}}">Employer</a></li>
            <li><a class="dropdown-item" href="{{url_for('applicant.applicant_login')}}">Applicant</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{{url_for('admin.admin_login')}}">Admin</a></li>
        </ul>
    </li>
{% endblock %}

{% block container %}

{% include 'job-search.html' %}

{% if jobs.page == 1 %}
    <section id="job-categories" class="bg-light py-5">
        <div class="container">
            <div class="p-3 mb-2 d-flex align-items-center">
                <p class="h2">Top Job Categories</p>
                <a href="{{ url_for('jobs.categories') }}" class="btn btn-sm prim btn-brand text-light ms-auto "> View All</a>
            </div> 
            
            <div class="row row-cols-xl-4 row-cols-lg-3 row-cols-md-2 row-cols-1 g-2">
                
                {% if categories %}
                    {% for category in categories[:4] %}
                        <div class="col">
                            <a href="{{ url_for('jobs.filtered', category=category) }}" class="admin-card category-card bg-white border d-block p-3 ">
                                <p class="h6"><i class="fa fa-tags me-2 t-prim"></i> {{category}}</p>
                                <div class="category-img-box">
                                    <div class ="image-box my-3">
                                        <img class="rounded-circle" src="{{url_for('static', filename='img/job_search.png')}}" alt="">
                                    </div>
                                    
                                    <div class ="views">
                                        <p class="h5 m-0 p-0">{{ filtered.filter_by(category=category).all() | length
                                        }}</p>
                                        <small class="text-muted p-0 m-0" >Total Jobs</small>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No available Job Categories</p>
                {% endif %}
                
            </div>
        </div>
    </section>
{% endif %}

<section id="jobs-list" class="bg-light py-5">
    <div class="container">
        <div class="section-header">
            <h2 class="">Recent Jobs</h2>
        </div>
        
        <div class="row row-cols-lg-3 row-cols-md-2 row-cols-1 g-2">
            {% if jobs %}
                {% for job in jobs.items %}
                    <div class="col">
                        <div class="bg-white border p-3 jobs-card h-100">
                            <div class="d-flex">
                                <div class="">
                                    <a href="{{ url_for('employer.profile', company_id=job.company.id) }}" class="profile-img-ctn prof-sm">
                                        <img src="{{ url_for('static', filename='employer/logo/' + job.company.logo) }}" alt="">
                                    </a>
                                </div>
                                <div class="w-100 ms-2">
                                    <div class="border-bottom d-flex align-items-center">
                                        <small class="text-muted"><i class="fa fa-calendar t-prim"></i> {{ job.date_posted.strftime("%d %b, %Y") }}</small>

                                        {% if current_user.is_authenticated and current_user.applicants and job in current_user.applicants.applied_jobs %}
                                            <span class="text-success ms-auto">Applied <i class="fa fa-check-square-o"></i></span>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="">
                                <h3 class="d-block text-dark m-0">{{ job.title }}</h3>
                                <p class="text-muted"><i class="fa fa-map-marker t-prim"></i> {{ job.company.location }}</p>
                                <p class="d-flex m-0 align-items-end">


                                    {% if job.salary %}
                                        <small><i class="fa fa-money t-prim"></i> KSh. {{ job.salary | numberFormat}}</small>
                                    {% else %}
                                        <small><i class="fa fa-money t-prim"></i> KSh. Not Specified</small>
                                    {% endif %}


                                    <a href="{{ url_for('jobs.profile', job_id=job.id) }}" class="btn btn-sm btn-brand prim text-light ms-auto">{{ job.type }}</a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No Posted Jobs yet. Check later.</p>
            {% endif %}
        </div>
        {% if jobs.total > jobs.per_page %}
            {% for page_num in jobs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if jobs.page == page_num %}
                        <a href="{{ url_for('jobs.job_list', page=page_num) }}" class="btn btn-sm btn-primary my-3">{{ page_num }}</a>
                    {% else %}
                        <a href="{{ url_for('jobs.job_list', page=page_num) }}" class="btn btn-sm btn-outline-primary my-3">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</section>

{% endblock %}
{% block script %}{% endblock %}